version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tender_db
      - JWT_SECRET=your-secret-key
      - PORT=8080
    volumes:
      - .:/app

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tender_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: